package com.example.demo.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table le_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class LoveUser {
    /**
     * Database Column Remarks:
     *   主id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   登录名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.login_name
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     * Database Column Remarks:
     *   中文名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.cn_name
     *
     * @mbg.generated
     */
    private String cnName;

    /**
     * Database Column Remarks:
     *   英文名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.en_name
     *
     * @mbg.generated
     */
    private String enName;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     * Database Column Remarks:
     *   身份证
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.identity_id
     *
     * @mbg.generated
     */
    private String identityId;

    /**
     * Database Column Remarks:
     *   身份证加密
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.identity_encrypt
     *
     * @mbg.generated
     */
    private String identityEncrypt;

    /**
     * Database Column Remarks:
     *   登录密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   性别：0：男，1：女
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     * Database Column Remarks:
     *   年龄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     * Database Column Remarks:
     *   出生年月日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   省
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.province
     *
     * @mbg.generated
     */
    private Integer province;

    /**
     * Database Column Remarks:
     *   市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.city
     *
     * @mbg.generated
     */
    private Integer city;

    /**
     * Database Column Remarks:
     *   区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.area
     *
     * @mbg.generated
     */
    private Integer area;

    /**
     * Database Column Remarks:
     *   所在地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   最后登录时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.last_login_time
     *
     * @mbg.generated
     */
    private Date lastLoginTime;

    /**
     * Database Column Remarks:
     *   创建人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.create_id
     *
     * @mbg.generated
     */
    private String createId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.update_id
     *
     * @mbg.generated
     */
    private String updateId;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   状态：1正常，2删除。。。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.id
     *
     * @return the value of le_user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.id
     *
     * @param id the value for le_user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.login_name
     *
     * @return the value of le_user.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.login_name
     *
     * @param loginName the value for le_user.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.cn_name
     *
     * @return the value of le_user.cn_name
     *
     * @mbg.generated
     */
    public String getCnName() {
        return cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.cn_name
     *
     * @param cnName the value for le_user.cn_name
     *
     * @mbg.generated
     */
    public void setCnName(String cnName) {
        this.cnName = cnName == null ? null : cnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.en_name
     *
     * @return the value of le_user.en_name
     *
     * @mbg.generated
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.en_name
     *
     * @param enName the value for le_user.en_name
     *
     * @mbg.generated
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.tel
     *
     * @return the value of le_user.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.tel
     *
     * @param tel the value for le_user.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.identity_id
     *
     * @return the value of le_user.identity_id
     *
     * @mbg.generated
     */
    public String getIdentityId() {
        return identityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.identity_id
     *
     * @param identityId the value for le_user.identity_id
     *
     * @mbg.generated
     */
    public void setIdentityId(String identityId) {
        this.identityId = identityId == null ? null : identityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.identity_encrypt
     *
     * @return the value of le_user.identity_encrypt
     *
     * @mbg.generated
     */
    public String getIdentityEncrypt() {
        return identityEncrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.identity_encrypt
     *
     * @param identityEncrypt the value for le_user.identity_encrypt
     *
     * @mbg.generated
     */
    public void setIdentityEncrypt(String identityEncrypt) {
        this.identityEncrypt = identityEncrypt == null ? null : identityEncrypt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.password
     *
     * @return the value of le_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.password
     *
     * @param password the value for le_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.sex
     *
     * @return the value of le_user.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.sex
     *
     * @param sex the value for le_user.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.age
     *
     * @return the value of le_user.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.age
     *
     * @param age the value for le_user.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.birthday
     *
     * @return the value of le_user.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.birthday
     *
     * @param birthday the value for le_user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.province
     *
     * @return the value of le_user.province
     *
     * @mbg.generated
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.province
     *
     * @param province the value for le_user.province
     *
     * @mbg.generated
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.city
     *
     * @return the value of le_user.city
     *
     * @mbg.generated
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.city
     *
     * @param city the value for le_user.city
     *
     * @mbg.generated
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.area
     *
     * @return the value of le_user.area
     *
     * @mbg.generated
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.area
     *
     * @param area the value for le_user.area
     *
     * @mbg.generated
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.address
     *
     * @return the value of le_user.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.address
     *
     * @param address the value for le_user.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.last_login_time
     *
     * @return the value of le_user.last_login_time
     *
     * @mbg.generated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.last_login_time
     *
     * @param lastLoginTime the value for le_user.last_login_time
     *
     * @mbg.generated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.create_id
     *
     * @return the value of le_user.create_id
     *
     * @mbg.generated
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.create_id
     *
     * @param createId the value for le_user.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.create_time
     *
     * @return the value of le_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.create_time
     *
     * @param createTime the value for le_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.update_id
     *
     * @return the value of le_user.update_id
     *
     * @mbg.generated
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.update_id
     *
     * @param updateId the value for le_user.update_id
     *
     * @mbg.generated
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.update_time
     *
     * @return the value of le_user.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.update_time
     *
     * @param updateTime the value for le_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user.state
     *
     * @return the value of le_user.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user.state
     *
     * @param state the value for le_user.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}