package com.example.demo.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table le_user_login_log
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class LoveUserLoginLog {
    /**
     * Database Column Remarks:
     *   主id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user_login_log.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user_login_log.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   登录时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user_login_log.login_time
     *
     * @mbg.generated
     */
    private Date loginTime;

    /**
     * Database Column Remarks:
     *   登录地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user_login_log.login_address
     *
     * @mbg.generated
     */
    private String loginAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user_login_log.id
     *
     * @return the value of le_user_login_log.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user_login_log.id
     *
     * @param id the value for le_user_login_log.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user_login_log.user_id
     *
     * @return the value of le_user_login_log.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user_login_log.user_id
     *
     * @param userId the value for le_user_login_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user_login_log.login_time
     *
     * @return the value of le_user_login_log.login_time
     *
     * @mbg.generated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user_login_log.login_time
     *
     * @param loginTime the value for le_user_login_log.login_time
     *
     * @mbg.generated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column le_user_login_log.login_address
     *
     * @return the value of le_user_login_log.login_address
     *
     * @mbg.generated
     */
    public String getLoginAddress() {
        return loginAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column le_user_login_log.login_address
     *
     * @param loginAddress the value for le_user_login_log.login_address
     *
     * @mbg.generated
     */
    public void setLoginAddress(String loginAddress) {
        this.loginAddress = loginAddress == null ? null : loginAddress.trim();
    }
}