package com.example.demo.dao;

import com.example.demo.bean.LoveUserLoginLog;
import com.example.demo.bean.LoveUserLoginLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoveUserLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user_login_log
     *
     * @mbg.generated
     */
    long countByExample(LoveUserLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user_login_log
     *
     * @mbg.generated
     */
    int deleteByExample(LoveUserLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user_login_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user_login_log
     *
     * @mbg.generated
     */
    int insert(LoveUserLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user_login_log
     *
     * @mbg.generated
     */
    int insertSelective(LoveUserLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user_login_log
     *
     * @mbg.generated
     */
    List<LoveUserLoginLog> selectByExample(LoveUserLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user_login_log
     *
     * @mbg.generated
     */
    LoveUserLoginLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user_login_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LoveUserLoginLog record, @Param("example") LoveUserLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user_login_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LoveUserLoginLog record, @Param("example") LoveUserLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user_login_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LoveUserLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user_login_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LoveUserLoginLog record);
}