package com.example.demo.dao;

import com.example.demo.bean.LoveUser;
import com.example.demo.bean.LoveUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoveUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user
     *
     * @mbg.generated
     */
    long countByExample(LoveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user
     *
     * @mbg.generated
     */
    int deleteByExample(LoveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user
     *
     * @mbg.generated
     */
    int insert(LoveUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user
     *
     * @mbg.generated
     */
    int insertSelective(LoveUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user
     *
     * @mbg.generated
     */
    List<LoveUser> selectByExample(LoveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user
     *
     * @mbg.generated
     */
    LoveUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LoveUser record, @Param("example") LoveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LoveUser record, @Param("example") LoveUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LoveUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table le_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LoveUser record);
}