package com.example.demo.entity.dto;

import lombok.Data;

import java.util.Date;

/**
 * 创建人:连磊
 * 日期: 2018/8/10. 16:48
 * 描述：
 */
@Data
public class UserRegisterDto {

    private String loginName;

    /**
     * Database Column Remarks:
     *   中文名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.cn_name
     *
     * @mbg.generated
     */
    private String cnName;

    /**
     * Database Column Remarks:
     *   英文名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.en_name
     *
     * @mbg.generated
     */
    private String enName;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     * Database Column Remarks:
     *   身份证
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.identity_id
     *
     * @mbg.generated
     */
    private String identityId;

    /**
     * Database Column Remarks:
     *   身份证加密
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.identity_encrypt
     *
     * @mbg.generated
     */
    private String identityEncrypt;

    /**
     * Database Column Remarks:
     *   登录密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   性别：0：男，1：女
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     * Database Column Remarks:
     *   年龄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     * Database Column Remarks:
     *   出生年月日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   省
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.province
     *
     * @mbg.generated
     */
    private Integer province;

    /**
     * Database Column Remarks:
     *   市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.city
     *
     * @mbg.generated
     */
    private Integer city;

    /**
     * Database Column Remarks:
     *   区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.area
     *
     * @mbg.generated
     */
    private Integer area;

    /**
     * Database Column Remarks:
     *   所在地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column le_user.address
     *
     * @mbg.generated
     */
    private String address;

}
